###服务启动端口号
server:
  port: 80
###服务名称(服务注册到eureka名称)
spring:
  application:
    name: app-zuul
###服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka

### 配置网关反向代理
zuul:
  routes:
    api-user:
      path: /api-user/**
      serviceId: app-user
    api-email:
      path: /api-email/**
      serviceId: app-email